replicaCount: 1
app: auth-gateway

image:
  repository: auth-gateway
  tag: "latest"
  pullPolicy: IfNotPresent

config:
  enabled: true
  data:
    SPRING_PROFILES_ACTIVE: "dev"
    SERVER_PORT: "8080"
    # Redis
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
    REDIS_DATABASE: "0"
    REDIS_SSL_ENABLED: "false"
    REDIS_COMMAND_TIMEOUT: "2000"
    REDIS_CONNECT_TIMEOUT: "2000"

    OAUTH_ISSUER_URI: "https://public.goorm.store"
    OAUTH_JWK_SET_URI: "https://public.goorm.store/jwks.json"
    OAUTH_AUDIENCE: "goormdotcom-aud"

secrets:
  enabled: true
  name: goorm/msa/secret
  data:
    - key: REDIS_HOST
      property: redis.host
    - key: REDIS_PORT
      property: redis.port
    - key: REDIS_DATABASE
      property: redis.database
    - key: REDIS_PASSWORD
      property: redis.password
