{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goorm-app.fullname" . }}-config
  labels:
    {{- include "goorm-app.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config.data }}
  {{ $key }}: "{{ $val }}"
  {{- end }}
{{- end }}


