{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "goorm-app.fullname" . }}-external
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "goorm-app.fullname" . }}-env
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.data }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ .Values.secrets.name }}
        property: {{ $property }}
    {{- end }}
{{- end }}