{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "goorm-app.fullname" . }}-external
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.secrets.secretStoreRef.name }}
    kind: {{ .Values.secrets.secretStoreRef.kind }}
  target:
    name: {{ include "goorm-app.fullname" . }}-env
    creationPolicy: Owner
  data:
    {{- range .Values.secrets.data }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ $.Values.secrets.name }}
        property: {{ .property }}
    {{- end }}
{{- end }}