apiVersion: v1
kind: Service
metadata:
  name: { { include "goorm-app.fullname" . } }
  labels: { { - include "goorm-app.labels" . | nindent 4 } }
spec:
  type: ClusterIP
  selector: { { - include "goorm-app.selectorLabels" . | nindent 4 } }
  ports:
    - name: http
      port: 8080
      targetPort: 8080
