replicaCount: 1
app: user
fullnameOverride: user

image:
  repository: 803733722005.dkr.ecr.ap-northeast-2.amazonaws.com/dev/user
  tag: "120301-arm"
  pullPolicy: IfNotPresent
  pullSecret: goorm-ecr-secret

config:
  enabled: true
  data:
    # Redis
    REDIS_SSL_ENABLED: "false"
    REDIS_COMMAND_TIMEOUT: "2000"
    REDIS_CONNECT_TIMEOUT: "2000"

    JWT_ISSUER: "https://public.goorm.store"
    JWT_AUDIENCE: "goormdotcom-aud"
    JWT_ACCESS_EXPIRATION: "3600"
    JWT_REFRESH_EXPIRATION: "86400"

secrets:
  enabled: true
  name: goorm/msa/secret
  secretStoreRef:
    name: goorm-app-secret-store
    kind: ClusterSecretStore
  data:
    - key: REDIS_HOST
      property: redis.host
    - key: REDIS_PORT
      property: redis.port
    - key: REDIS_DATABASE
      property: redis.database
    - key: REDIS_SSL_ENABLED
      property: redis.ssl_enabled
    - key: DB_URL
      property: user.db.url
    - key: DB_USERNAME
      property: user.db.username
    - key: DB_PASSWORD
      property: user.db.password
    - key: JWT_SECRET
      property: user.jwt_secret
