replicaCount: 1
app: order
fullnameOverride: order

image:
  repository: 803733722005.dkr.ecr.ap-northeast-2.amazonaws.com/dev/order
  tag: "121001"
  pullPolicy: IfNotPresent

config:
  enabled: true
  data:
    # Redis
    REDIS_SSL_ENABLED: "false"
    REDIS_COMMAND_TIMEOUT: "2000"
    REDIS_CONNECT_TIMEOUT: "2000"

secrets:
  enabled: true
  name: goorm/msa/secret
  secretStoreRef:
    name: goorm-app-secret-store
    kind: ClusterSecretStore
  data:
    - key: REDIS_HOST
      property: redis.host
    - key: REDIS_PORT
      property: redis.port
    - key: REDIS_DATABASE
      property: redis.database
    - key: REDIS_SSL_ENABLED
      property: redis.ssl_enabled
    - key: DB_URL
      property: order.db.url
    - key: DB_USERNAME
      property: order.db.username
    - key: DB_PASSWORD
      property: order.db.password
    - key: KAFKA_BOOTSTRAP_SERVERS
      property: spring.kafka.bootstrap.servers
    - key: KAFKA_SASL_USERNAME
      property: spring.kafka.username
    - key: KAFKA_SASL_PASSWORD
      property: spring.kafka.password
